# -*- coding: utf-8 -*-
"""pipeline4_dbscan.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t2IS5gCp5dwhqyh77QZulEzBoJhqpHUj
"""

import pandas as pd
import numpy as np
from sklearn.cluster import DBSCAN
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.ensemble import IsolationForest
from sklearn.metrics import mean_absolute_error
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeClassifier # Import Decision Tree Classifier
from sklearn.model_selection import train_test_split # Import train_test_split function
from sklearn import metrics #Import scikit-learn metrics module for accuracy calculation
import pickle

!git clone https://github.com/medaharrat/anomalies-detection

data=pd.read_csv("/content/anomalies-detection/spark/data/SWaT_train.csv")

X = data.iloc[:, data.columns != 'Time']

dbb=DBSCAN(eps=3,min_samples=5).fit(X)

with open('/content/anomalies-detection/spark/models/dbscan.pickle', 'wb') as f:
    pickle.dump(dbb, f)